version: '3'

services:
  db:
    image: postgres:14.3
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
      POSTGRES_DB: '${DATABASE_NAME}'
    container_name: igdatabase
    volumes:
      - psql:/var/lib/postgresql/data
volumes:
  psql: